redhat/kernel.spec.template: Add kernel-uki-dtbloader sub-package
Add a kernel-uki-dtbloader sub-package for:
https://fedoraproject.org/wiki/Changes/Automatic_DTB_selection_for_aarch64_EFI_systems

As described there this new package offers a standard kernel vmlinuz.efi
image which is to be booted normally through grub with grub passing
an initrd and the kernel cmdline.

Since this is essentially a replacement for the standard -core kernel
"kernel-install add" treats it as such (which is what we want) and this
causes it to use the same /boot/vmlinuz-$KernelVer and BLS .conf filenames
as it does for the -core package.

To avoid these file-conflicts the kernel[-variant]-uki-dtbloader pkg is
made to conflict with kernel[-variant]-core.

As mentioned in the Changes wiki page the long term plan (maybe for
Fedora 45) is to just replace the plain vmlinuz from kernel-core with
the vmlinuz with the systemd-stub + DTBs embedded and then drop
the uki-dtbloader sub-package, which would remove this Conflicts.

Signed-off-by: Hans de Goede <johannes.goede@oss.qualcomm.com>

diff --git a/redhat/kernel.spec.template b/redhat/kernel.spec.template
--- a/redhat/kernel.spec.template
+++ b/redhat/kernel.spec.template
@@ -342,6 +342,17 @@ Summary: The Linux kernel
 %define with_efiuki 0
 %endif
 
+%ifarch aarch64
+# dtbloader sub-package requires stubble which is only in Fedora for now
+%if 0%{?fedora}
+%define with_dtbloader %{?_without_dtbloader: 0} %{?!_without_dtbloader: 1}
+%else
+%define with_dtbloader 0
+%endif
+%else
+%define with_dtbloader 0
+%endif
+
 %if 0%{?fedora}
 # Kernel headers are being split out into a separate package
 %define with_headers 0
@@ -450,6 +461,7 @@ Summary: The Linux kernel
 %define with_selftests 0
 %define with_headers 0
 %define with_efiuki 0
+%define with_dtbloader 0
 %define with_zfcpdump 0
 %define with_arm64_16k 0
 %define with_arm64_64k 0
@@ -488,6 +500,7 @@ Summary: The Linux kernel
 %define with_selftests 0
 %define with_headers 0
 %define with_efiuki 0
+%define with_dtbloader 0
 %define with_zfcpdump 0
 %define with_vdso_install 0
 %define with_kabichk 0
@@ -517,6 +530,7 @@ Summary: The Linux kernel
 %define with_arm64_16k 0
 %define with_arm64_64k 0
 %define with_efiuki 0
+%define with_dtbloader 0
 %define with_doc 0
 %define with_headers 0
 %define with_cross_headers 0
@@ -948,15 +962,22 @@ BuildRequires: dracut
 BuildRequires: binutils
 # For the initrd
 BuildRequires: lvm2
-BuildRequires: systemd-boot-unsigned
 # For systemd-stub and systemd-pcrphase
 BuildRequires: systemd-udev >= 252-1
 # For systemd-repart
 BuildRequires: xfsprogs e2fsprogs dosfstools
-# For UKI kernel cmdline addons
-BuildRequires: systemd-ukify
 # For TPM operations in UKI initramfs
 BuildRequires: tpm2-tools
+%endif
+
+%if %{with_dtbloader}
+BuildRequires: stubble
+%endif
+
+%if %{with_efiuki} || %{with_dtbloader}
+BuildRequires: systemd-boot-unsigned
+# For UKI kernel cmdline addons
+BuildRequires: systemd-ukify
 # For UKI sb cert
 %if 0%{?rhel}%{?centos} && !0%{?eln}
 %if 0%{?centos}
@@ -1087,6 +1108,7 @@ Source77: partial-clang_lto-aarch64-debug-snip.config
 Source80: generate_all_configs.sh
 Source81: process_configs.sh
 
+Source82: dtbloader.sbat.template
 Source83: uki.sbat.template
 Source84: uki-addons.sbat.template
 Source85: kernel.sbat.template
@@ -1800,6 +1822,18 @@ Provides: installonlypkg(kernel)\
 Requires: %{name}%{?1:-%{1}}-uki-virt = %{specrpmversion}-%{release}\
 Requires(pre): systemd >= 254-1\
 %endif\
+%if %{with_dtbloader} && ("%{?1}" == "" || "%{1}" == "debug")\
+# This is not a full UKI, uki is in the name for compat with kernel_variant_posttrans -u\
+%package %{?1:%{1}-}uki-dtbloader\
+Summary: %{variant_summary} with systemd-stub for auto DTB loading\
+Provides: installonlypkg(kernel)\
+Provides: %{name}-uname-r = %{KVERREL}%{uname_suffix %{?1}}\
+Requires: %{name}%{?1:-%{1}}-modules-core-uname-r = %{KVERREL}%{uname_suffix %{?1}}\
+Requires(pre): %{kernel_prereq}\
+# "kernel-install add ..." treats this as a regular kernel, which is what we want.\
+# This causes a /boot/vmlinuz-$(uname -r) and BLS .conf file conflict with kernel-core.\
+Conflicts: %{name}%{?1:-%{1}}-core = %{specrpmversion}-%{release}\
+%endif\
 %if %{with_gcov}\
 %{expand:%%kernel_gcov_package %{?1:%{1}}}\
 %endif\
@@ -2027,6 +2061,16 @@ Prebuilt 64k unified kernel image for virtual machines.
 Prebuilt 64k unified kernel image addons for virtual machines.
 %endif
 
+%if %{with_stock} && %{with_debug} && %{with_dtbloader}
+%description debug-uki-dtbloader
+Prebuilt debug kernel image with auto DTB selection for ARM64 UEFI devices.
+%endif
+
+%if %{with_stock_base} && %{with_dtbloader}
+%description uki-dtbloader
+Prebuilt default kernel image with auto DTB selection for ARM64 UEFI devices.
+%endif
+
 %ifnarch noarch %{nobuildarches}
 %kernel_modules_extra_matched_package
 %endif
@@ -2154,6 +2198,7 @@ rm -f localversion-next localversion-rt
 	scripts/clang-tools 2> /dev/null
 
 # SBAT data
+sed -e s,@KVER,%{KVERREL}, -e s,@SBAT_SUFFIX,%{sbat_suffix}, %{SOURCE82} > dtbloader.sbat
 sed -e s,@KVER,%{KVERREL}, -e s,@SBAT_SUFFIX,%{sbat_suffix}, %{SOURCE83} > uki.sbat
 sed -e s,@KVER,%{KVERREL}, -e s,@SBAT_SUFFIX,%{sbat_suffix}, %{SOURCE84} > uki-addons.sbat
 sed -e s,@KVER,%{KVERREL}, -e s,@SBAT_SUFFIX,%{sbat_suffix}, %{SOURCE85} > kernel.sbat
@@ -2975,6 +3020,51 @@ BuildKernel() {
 	:  # in case of empty block
     fi # "$Variant" == "rt" || "$Variant" == "rt-debug" || "$Variant" == "automotive" || "$Variant" == "automotive-debug"
 
+%if %{with_dtbloader}
+    if [[ -z "$Variant" || "$Variant" == "debug" ]]; then
+	%{log_msg "Setup the DTB-loader kernel"}
+	DtbloaderImage="$RPM_BUILD_ROOT/lib/modules/$KernelVer/$InstallName-dtbloader.efi"
+	DtbPath=$RPM_BUILD_ROOT/%{image_install_path}/dtb-$KernelVer/qcom
+
+	pushd $DtbPath
+	Dtbs=""
+	for i in x1 sc8?80x; do
+	    Dtbs="$Dtbs $(ls $i*.dtb | grep -v -E 'el2|devkit|crd|qcp|primus')"
+	done
+	popd
+
+	DevicetreeAuto=""
+	for i in $Dtbs; do
+	    DevicetreeAuto="$DevicetreeAuto --devicetree-auto=$DtbPath/$i"
+	done
+
+	# os-release is unset, so that this is not seen as a full UKI by
+	# "kernel-install add" and instead is treated as a normal kernel image,
+	# causing kernel-install to generate an initrd + standard BLS cfg.
+	# This is also required for systemd-stub to work with a GRUB provided
+	# initramfs.
+	ukify build --linux=$(realpath $KernelImage) \
+	   --sbat=@dtbloader.sbat --os-release="" --uname=$KernelVer \
+	   --hwids=/usr/share/stubble/hwids $DevicetreeAuto --output=$DtbloaderImage
+
+%if %{signkernel}
+	%{log_msg "Sign the DTB-loader kernel"}
+	%pesign -s -i $DtbloaderImage -o $DtbloaderImage.signed -a %{secureboot_ca_0} -c %{secureboot_key_0} -n %{pesign_name_0}
+	if [ ! -s $DtbloaderImage.signed ]; then
+	    echo "pesigning failed"
+	    exit 1
+	fi
+	mv $DtbloaderImage.signed $DtbloaderImage
+%endif
+	chmod 755 $DtbloaderImage
+
+	%{log_msg "hmac sign the DTB-loader kernel for FIPS"}
+	pushd $(dirname $DtbloaderImage)
+	sha512hmac $(basename $DtbloaderImage) > .$(basename $DtbloaderImage).hmac
+	popd
+    fi # -z "$Variant" || "$Variant" == "debug"
+# with_dtbloader
+%endif
 
     #
     # Generate the modules files lists
@@ -4198,6 +4288,11 @@ fi\
 %kernel_variant_preun -u virt -e
 %endif
 
+%if %{with_stock_base} && %{with_dtbloader}
+%kernel_variant_posttrans -u dtbloader
+%kernel_variant_preun -u dtbloader
+%endif
+
 %if %{with_stock_base}
 %kernel_variant_preun -e
 %kernel_variant_post
@@ -4211,6 +4306,11 @@ fi\
 %if %{with_stock} && %{with_debug} && %{with_efiuki}
 %kernel_variant_posttrans -v debug -u virt
 %kernel_variant_preun -v debug -u virt -e
+%endif
+
+%if %{with_stock} && %{with_debug} && %{with_dtbloader}
+%kernel_variant_posttrans -v debug -u dtbloader
+%kernel_variant_preun -v debug -u dtbloader
 %endif
 
 %if %{with_stock} && %{with_debug}
@@ -4536,6 +4636,7 @@ fi\
 #   - kernel-devel: headers and build infrastructure
 #   - kernel-debuginfo: vmlinux with debug symbols (if with_debuginfo)
 #   - kernel-uki-virt: unified kernel image for VMs (if with_efiuki)
+#   - kernel-uki-dtbloader: kernel with systemd-stub for auto DTB loading (if with_dtbloader)
 #
 %define kernel_variant_files(k:) \
 %if %{2}\
@@ -4618,6 +4719,28 @@ fi\
 %{expand:%%files %{?3:%{3}-}uki-virt-addons}\
 %dir /lib/modules/%{KVERREL}%{?3:+%{3}}/%{?-k:%{-k*}}%{!?-k:vmlinuz}-virt.efi.extra.d/ \
 /lib/modules/%{KVERREL}%{?3:+%{3}}/%{?-k:%{-k*}}%{!?-k:vmlinuz}-virt.efi.extra.d/*.addon.efi\
+%endif\
+%if %{with_dtbloader} && ("%{?3}" == "" || "%{3}" == "debug")\
+%{expand:%%files %{?3:%{3}-}uki-dtbloader}\
+%%license linux-%{KVERREL}/COPYING-%{version}-%{release}\
+%dir /lib/modules\
+%dir /lib/modules/%{KVERREL}%{?3:+%{3}}\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/System.map\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/config\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/modules.builtin*\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/symvers.%compext\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/%{?-k:%{-k*}}%{!?-k:vmlinuz}-dtbloader.efi\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/.%{?-k:%{-k*}}%{!?-k:vmlinuz}-dtbloader.efi.hmac\
+%ghost %attr(0644, root, root) /boot/System.map-%{KVERREL}%{?3:+%{3}}\
+%ghost %attr(0644, root, root) /boot/config-%{KVERREL}%{?3:+%{3}}\
+%ghost %attr(0600, root, root) /boot/initramfs-%{KVERREL}%{?3:+%{3}}.img\
+%ghost %attr(0644, root, root) /boot/symvers-%{KVERREL}%{?3:+%{3}}.%compext\
+%ghost %attr(0755, root, root) /%{image_install_path}/%{?-k:%{-k*}}%{!?-k:vmlinuz}-%{KVERREL}%{?3:+%{3}}\
+%ghost %attr(0644, root, root) /%{image_install_path}/.%{?-k:%{-k*}}%{!?-k:vmlinuz}-%{KVERREL}%{?3:+%{3}}.hmac\
+%ifarch aarch64 riscv64\
+/lib/modules/%{KVERREL}%{?3:+%{3}}/dtb \
+%ghost /%{image_install_path}/dtb-%{KVERREL}%{?3:+%{3}} \
+%endif\
 %endif\
 %if %{?3:1} %{!?3:0}\
 %{expand:%%files %{3}}\
